// Amtrak API timezone code to IANA timezone database name map
export const amtrakTZCodeToTZDB: Record<AmtrakTZCode, string> = {
  P: 'America/Los_Angeles',
  M: 'America/Denver',
  C: 'America/Chicago',
  E: 'America/New_York',
}

// Amtrak station code to station name map
// Source: https://github.com/piemadd/amtraker-v3/blob/main/data/stations.ts
export const amtrakStationCodeToName: Record<string, string> = {
  ABE: 'Aberdeen',
  ABN: 'Absecon',
  ACY: 'Atlantic City',
  ALY: 'Albany',
  ALB: 'Albany-Rensselaer',
  ALI: 'Albion',
  ABQ: 'Albuquerque',
  AST: 'Aldershot',
  ALD: 'Alderson',
  ALX: 'Alexandria',
  CNL: 'Allensworth State Park',
  ALC: 'Alliance',
  ALP: 'Alpine',
  ALN: 'Alton',
  ALT: 'Altoona',
  AMS: 'Amsterdam',
  ANA: 'Anaheim',
  ARB: 'Ann Arbor',
  ATN: 'Anniston',
  ACA: 'Antioch-Pittsburg',
  ACD: 'Arcadia Valley',
  ADM: 'Ardmore',
  ARD: 'Ardmore',
  ARK: 'Arkadelphia',
  AKY: 'Ashland',
  ASD: 'Ashland',
  ATL: 'Atlanta Peachtree',
  ATO: 'Atco',
  ARN: 'Auburn',
  AUS: 'Austin',
  BFD: 'Bakersfield',
  BAL: 'Baltimore Penn',
  BAM: 'Bangor',
  BAR: 'Barstow',
  BTL: 'Battle Creek',
  BMT: 'Beaumont',
  BEL: 'Bellingham Fairhaven',
  BLF: 'Bellows Falls',
  BEN: 'Benson',
  BKY: 'Berkeley',
  BER: 'Berlin',
  BNF: 'Branford',
  BNG: 'Bingen-White Salmon',
  BHM: 'Birmingham',
  BNL: 'Bloomington-Normal',
  BBY: 'Boston Back Bay',
  BON: 'Boston North',
  BOS: 'Boston South',
  BRA: 'Brattleboro',
  BRP: 'Bridgeport',
  BRH: 'Brookhaven',
  BRO: 'Browning',
  BRK: 'Brunswick',
  BYN: 'Bryan',
  BUF: 'Buffalo-Depew',
  BFX: 'Buffalo-Exchange Street',
  BUR: 'Burbank Airport',
  BBK: 'Burbank',
  BCV: 'Burke Centre',
  BRL: 'Burlington',
  BNC: 'Burlington',
  BTN: 'Burlington',
  BWI: 'Baltimore Airport',
  CML: 'Camarillo',
  CAM: 'Camden',
  CDL: 'Carbondale',
  CRV: 'Carlinville',
  CPN: 'Carpinteria',
  CYN: 'Cary',
  CNV: 'Castleton',
  CEN: 'Centralia',
  CTL: 'Centralia',
  CHM: 'Champaign-Urbana',
  CHS: 'Charleston',
  CHW: 'Charleston',
  CLT: 'Charlotte',
  CVS: 'Charlottesville',
  CWT: 'Chatsworth',
  CMO: 'Chemult',
  CHI: 'Chicago Union',
  CIC: 'Chico',
  CIN: 'Cincinnati',
  CLA: 'Claremont',
  CBR: 'Cleburne',
  CSN: 'Clemson',
  CLE: 'Cleveland',
  CLF: 'Clifton Forge',
  COT: 'Coatesville',
  COX: 'Colfax',
  CLB: 'Columbia',
  CBS: 'Columbus',
  COV: 'Connellsville',
  COI: 'Connersville',
  COC: 'Corcoran',
  CWH: 'Cornwells Heights',
  CRF: 'Crawfordsville',
  CRH: 'Charry Hill',
  CRN: 'Creston',
  CRT: 'Croton-Harmon',
  CLM: 'Claremont',
  CLN: 'Clinton',
  CLP: 'Culpeper',
  CUM: 'Cumberland',
  CUT: 'Cut Bank',
  DAL: 'Dallas',
  DAN: 'Danville',
  DAV: 'Davis',
  DER: 'Dearborn',
  DFB: 'Deerfield Beach',
  DRT: 'Del Rio',
  DLD: 'DeLand',
  DLB: 'Delray Beach',
  DEM: 'Deming',
  DNK: 'Denmark',
  DEN: 'Denver',
  DET: 'Detroit',
  DLK: 'Detroit Lakes',
  DVL: 'Devils Lake',
  DIL: 'Dillon',
  DDG: 'Dodge City',
  DOV: 'Dover',
  DOA: 'Dowagiac',
  DOW: 'Downingtown',
  DQN: 'Du Quoin',
  DUN: 'Dunsmuir',
  DRD: 'Durand',
  DNC: 'Durham',
  DHM: 'Durham-UNH',
  DWT: 'Dwight',
  DYE: 'Dyer',
  GPK: 'East Glacier Park',
  LNS: 'East Lansing',
  EDM: 'Edmonds',
  EFG: 'Effingham',
  EGH: 'Egg Harbor',
  ELP: 'El Paso',
  EKH: 'Elkhart',
  ELT: 'Elizabethtown',
  ELK: 'Elko',
  ELY: 'Elyria',
  EMY: 'Emeryville',
  EPH: 'Ephrata',
  ERI: 'Erie',
  ESM: 'Essex',
  ESX: 'Essex Junction',
  EUG: 'Eugene-Springfield',
  EVR: 'Everett',
  EXR: 'Exeter',
  EXT: 'Exton',
  FFV: 'Fairfield-Vacaville',
  FAL: 'Falmouth',
  FAR: 'Fargo',
  FAY: 'Fayetteville',
  VRN: 'Ferrisburgh-Vergennes',
  FLG: 'Flagstaff',
  FLN: 'Flint',
  FLO: 'Florence',
  FED: 'Fort Edward',
  FTL: 'Fort Lauderdale',
  FMD: 'Fort Madison',
  FMG: 'Fort Morgan',
  FTW: 'Fort Worth',
  FRA: 'Framingham',
  WIP: 'Fraser-Winter Park',
  FBG: 'Fredericksburg',
  FRE: 'Freeport',
  FMT: 'Fremont',
  FNO: 'Fresno',
  FUL: 'Fullerton',
  FTN: 'Fulton',
  GNS: 'Gainesville',
  GLE: 'Gainesville',
  GBB: 'Galesburg',
  GLP: 'Gallup',
  GCK: 'Garden City',
  GCN: 'Grand Canyon',
  GAS: 'Gastonia',
  GLM: 'Gilman',
  GGW: 'Glasgow',
  GDL: 'Glendale',
  GLN: 'Glenview',
  GSC: 'Glenwood Springs',
  GTA: 'Goleta',
  GRA: 'Granby',
  GFK: 'Grand Forks',
  GJT: 'Grand Junction',
  GRR: 'Grand Rapids',
  GRI: 'Green River',
  GFD: 'Greenfield',
  GRO: 'Greensboro',
  GNB: 'Greensburg',
  GRV: 'Greenville',
  GWD: 'Greenwood',
  GMS: 'Grimsby',
  GVB: 'Grover Beach',
  GUA: 'Guadalupe',
  GUI: 'Guilford',
  HAM: 'Hamlet',
  HMD: 'Hammond',
  HMI: 'Hammond/Whiting',
  HNF: 'Hanford',
  HFY: 'Harpers Ferry',
  HAR: 'Harrisburg',
  HFD: 'Hartford',
  HAS: 'Hastings',
  HBG: 'Hattiesburg',
  HHL: 'Haverhill',
  HAV: 'Havre',
  HAY: 'Hayward',
  HAZ: 'Hazlehurst',
  HER: 'Helper',
  HEM: 'Hermann',
  HPT: 'High Point',
  HIN: 'Hinton',
  HLD: 'Holdrege',
  HOM: 'Holland',
  HOL: 'Hollywood',
  HLK: 'Holyoke',
  HMW: 'Homewood',
  HOP: 'Hope',
  HOS: 'Houston',
  HUD: 'Hudson',
  HGD: 'Huntingdon',
  HTN: 'Hammonton',
  HUN: 'Huntington',
  HUT: 'Hutchinson',
  IDP: 'Independence',
  IND: 'Indianapolis',
  IRV: 'Irvine',
  JXN: 'Jackson',
  JAN: 'Jackson',
  JAX: 'Jacksonville',
  JEF: 'Jefferson City',
  JSP: 'Jesup',
  JST: 'Johnstown',
  JOL: 'Joliet',
  KAL: 'Kalamazoo',
  KKI: 'Kankakee',
  KAN: 'Kannapolis',
  KCY: 'Kansas City',
  KEL: 'Kelso',
  KEE: 'Kewanee',
  KNG: 'Kingman',
  KIN: 'Kingston',
  KTR: 'Kingstree',
  KWD: 'Kirkwood',
  KIS: 'Kissimmee',
  KFS: 'Klamath Falls',
  LSE: 'La Crosse',
  LAG: 'La Grange Road',
  LAJ: 'La Junta',
  LAP: 'La Plata',
  LAF: 'Lafayette',
  LFT: 'Lafayette',
  LCH: 'Lake Charles',
  LDW: 'Somerdale',
  LAK: 'Lakeland',
  LKL: 'Lakeland',
  LMR: 'Lamar',
  LMY: 'Lamy',
  LNC: 'Lancaster',
  LPE: 'Lapeer',
  LSV: 'Las Vegas',
  LAB: 'Latrobe',
  LAU: 'Laurel',
  LRC: 'Lawrence',
  LWA: 'Leavenworth',
  LEE: "Lee's Summit",
  LEW: 'Lewistown',
  LEX: 'Lexington',
  LIB: 'Libby',
  LCN: 'Lincoln',
  LNK: 'Lincoln',
  LRK: 'Little Rock',
  VAS: 'Livermore',
  LOD: 'Lodi',
  LPS: 'Lompoc-Surf',
  LTM: 'Manteca',
  LVW: 'Longview',
  LDB: 'Lordsburg',
  LOR: 'Lorton',
  LAX: 'Los Angeles Union',
  LYH: 'Lynchburg-Kemper Street',
  MAC: 'Macomb',
  MAD: 'Madera',
  MAL: 'Malta',
  MDR: 'Madera',
  MDV: 'Madisonville',
  MDS: 'Madison',
  MVN: 'Malvern',
  MSS: 'Manassas',
  MRC: 'Maricopa',
  MKS: 'Marks',
  MHL: 'Marshall',
  MTZ: 'Martinez',
  MRB: 'Martinsburg',
  MAT: 'Mattoon',
  MAY: 'Maysville',
  MCB: 'McComb',
  MCK: 'McCook',
  MCG: 'McGregor',
  MEM: 'Memphis Central',
  MDT: 'Mendota',
  MCD: 'Merced',
  MDN: 'Meriden',
  MEI: 'Meridian',
  MET: 'Metropark',
  MIA: 'Miami',
  MCI: 'Michigan City',
  MBY: 'Middlebury',
  MID: 'Middletown',
  MKE: 'Milwaukee',
  MKA: 'Milwaukee Airport',
  MIN: 'Mineola',
  MOT: 'Minot',
  MOD: 'Modesto',
  MNG: 'Montgomery',
  MPR: 'Montpelier',
  MTR: 'Montreal',
  MPK: 'Moorpark',
  MJY: 'Mount Joy',
  MTP: 'Mount Pleasant',
  MVW: 'Mount Vernon',
  MYS: 'Mystic',
  MYU: 'Seaside-Marina',
  NPV: 'Naperville',
  NDL: 'Needles',
  NBK: 'New Brunswick',
  NBU: 'New Buffalo',
  NCR: 'New Carrollton',
  NHV: 'New Haven Union',
  STS: 'New Haven State Street',
  NIB: 'New Iberia',
  NLC: 'New London',
  NOL: 'New Orleans',
  NRO: 'New Rochelle',
  NYP: 'New York Penn',
  NYF: 'New York State Fair',
  NRK: 'Newark',
  EWR: 'Newark Airport',
  NWK: 'Newark Penn',
  NBN: 'Newbern-Dyersburg',
  NPN: 'Newport News',
  NEW: 'Newton',
  NFL: 'Niagara Falls (United States)',
  NFS: 'Niagara Falls (Canada)',
  NLS: 'Niles',
  NFK: 'Norfolk',
  NOR: 'Norman',
  NSF: 'North Carolina State Fair',
  NHT: 'Northampton',
  NRG: 'Northridge',
  OAC: 'Oakland Coliseum',
  OKJ: 'Oakland-Jack London Square',
  OKL: 'Oakville',
  OSD: 'Oceanside',
  OKE: 'Okeechobee',
  OKC: 'Oklahoma City',
  ORB: 'Old Orchard Beach',
  OLW: 'Lacey',
  OSB: 'Old Saybrook',
  OWL: 'Olympia-Lacey',
  OMA: 'Omaha',
  ONA: 'Ontario',
  ORC: 'Oregon City',
  ORL: 'Orlando',
  OSC: 'Osceola',
  OTM: 'Ottumwa',
  OXN: 'Oxnard',
  PAK: 'Palatka',
  PSN: 'Palm Springs',
  PAO: 'Paoli',
  PAR: 'Parkesburg',
  PSC: 'Pasco',
  PRB: 'Paso Robles',
  PTB: 'Petersburg',
  PVL: 'Pauls Valley',
  PHL: 'Philadelphia 30th Street',
  PHN: 'Philadelphia North',
  PIC: 'Picayune',
  PGH: 'Pittsburgh',
  PIT: 'Pittsfield',
  PLO: 'Plano',
  PNK: 'Pennsauken',
  PLS: 'Pleasanton',
  PLB: 'Plattsburgh',
  POS: 'Pomona',
  PON: 'Pontiac',
  PNT: 'Pontiac',
  PBF: 'Poplar Bluff',
  POH: 'Port Henry',
  PTH: 'Port Huron',
  PRK: 'Port Kent',
  POG: 'Portage',
  POR: 'Portland',
  PDX: 'Portland',
  POU: 'Poughkeepsie',
  PRC: 'Prince',
  PCT: 'Princeton',
  PJC: 'Princeton Junction',
  PVD: 'Providence',
  PRO: 'Provo',
  PUR: 'Purcell',
  QAN: 'Quantico',
  QCY: 'Quincy',
  RGH: 'Raleigh Union',
  RPH: 'Randolph',
  RTL: 'Rantoul',
  RAT: 'Raton',
  RDW: 'Red Wing',
  RDD: 'Redding',
  RNO: 'Reno',
  REN: 'Rensselaer',
  RHI: 'Rhinecliff-Kingston',
  RIC: 'Richmond',
  RVR: 'Richmond Staples Mill Road',
  RVM: 'Richmond Main Street',
  RIV: 'Riverside',
  RNK: 'Roanoke',
  ROC: 'Rochester',
  RLN: 'Rocklin',
  RMT: 'Rocky Mount',
  RKV: 'Rockville',
  ROM: 'Rome',
  RSV: 'Roseville',
  RSP: 'Rouses Point',
  ROY: 'Royal Oak',
  RUG: 'Rugby',
  RUD: 'Rutland',
  SAO: 'Saco-Biddeford',
  SAC: 'Sacramento',
  SLM: 'Salem',
  SNS: 'Salinas',
  SAL: 'Salisbury',
  SLC: 'Salt Lake City',
  SAS: 'San Antonio',
  SNB: 'San Bernardino',
  SNP: 'San Clemente Pier',
  OLT: 'San Diego Old Town',
  SAN: 'San Diego Santa Fe Depot',
  SJC: 'San Jose Diridon',
  SNC: 'San Juan Capistrano',
  SLO: 'San Luis Obispo',
  SMC: 'San Marcos',
  SND: 'Sanderson',
  SPT: 'Sandpoint',
  SKY: 'Sandusky',
  SFA: 'Sanford',
  SNA: 'Santa Ana',
  SBA: 'Santa Barbara',
  GAC: 'Santa Clara - Great America',
  SCC: 'Santa Clara',
  SAR: 'Saratoga Springs',
  SAV: 'Savannah',
  SDY: 'Schenectady',
  SCH: 'Schriever',
  SEA: 'Seattle King Street',
  SBG: 'Sebring',
  SED: 'Sedalia',
  SSM: 'Selma',
  SBY: 'Shelby',
  SIM: 'Simi Valley',
  SDL: 'Slidell',
  SOL: 'Solana Beach',
  SOB: 'South Bend',
  SPM: 'South Portsmouth-South Shore',
  SOP: 'Southern Pines',
  SPB: 'Spartanburg',
  SPK: 'Spokane',
  SPI: 'Springfield',
  SPG: 'Springfield',
  SAB: 'St. Albans',
  SCA: 'St. Catharines',
  SCD: 'St. Cloud',
  SJM: 'St. Joseph-Benton Harbor',
  SLQ: 'Saint-Lambert',
  STL: 'St. Louis Gateway',
  MSP: 'St. Paul - Minneapolis Union',
  STM: 'Stamford',
  STN: 'Stanley',
  STW: 'Stanwood',
  SPL: 'Staples',
  STA: 'Staunton',
  SKT: 'Stockton Downtown',
  SKN: 'Stockton San Joaquin Street',
  SVT: 'Sturtevant',
  SUI: 'Suisun-Fairfield',
  SMT: 'Summit',
  SYR: 'Syracuse',
  TAC: 'Tacoma Dome',
  TPA: 'Tampa',
  TAY: 'Taylor',
  TPL: 'Temple',
  TXA: 'Texarkana',
  THN: 'Thurmond',
  FTC: 'Ticonderoga',
  TCA: 'Toccoa',
  TOL: 'Toledo',
  TOH: 'Tomah',
  TOP: 'Topeka',
  TWO: 'Toronto Union',
  TRC: 'Tracy',
  TRE: 'Trenton',
  TRI: 'Trinidad',
  TRM: 'Troy',
  TRU: 'Truckee',
  TUS: 'Tucson',
  TUK: 'Tukwila',
  TRK: 'Turlock-Denair',
  TCL: 'Tuscaloosa',
  TYR: 'Tyrone',
  UCA: 'Utica',
  VNC: 'Van Nuys',
  VAC: 'Vancouver Pacific Central',
  VAN: 'Vancouver',
  VEC: 'Ventura',
  VRV: 'Victorville',
  WFD: 'Wallingford',
  WNR: 'Walnut Ridge',
  WAR: 'Warrensburg',
  WAC: 'Wasco',
  WAS: 'Washington Union',
  WAH: 'Washington',
  WAB: 'Waterbury-Stowe',
  WTI: 'Waterloo',
  WEM: 'Wells',
  WEN: 'Wenatchee',
  WGL: 'West Glacier',
  WPB: 'West Palm Beach',
  WLY: 'Westerly',
  WSB: 'Westbrook',
  WSP: 'Westport',
  RTE: 'Westwood-Route 128',
  WRJ: 'White River Junction',
  WSS: 'White Sulphur Springs',
  WFH: 'Whitefish',
  WHL: 'Whitehall',
  WMA: 'Williams',
  WBG: 'Williamsburg',
  WTN: 'Williston',
  WIL: 'Wilmington',
  WLN: 'Wilson',
  WND: 'Windsor',
  WNM: 'Windsor-Mt. Ascutney',
  WNL: 'Windsor Locks',
  WNN: 'Winnemucca',
  WIN: 'Winona',
  WLO: 'Winslow',
  WTH: 'Winter Haven',
  WPR: 'Winter Park Resort',
  WPK: 'Winter Park',
  WDL: 'Wisconsin Dells',
  WIH: 'Wishram',
  WOB: 'Woburn-Anderson',
  WPT: 'Wolf Point',
  WDB: 'Woodbridge',
  WOR: 'Worcester',
  YAZ: 'Yazoo City',
  YEM: 'Yemassee',
  YNY: 'Yonkers',
  YUM: 'Yuma',
  ATR: 'Atmore',
  BAS: 'Bay St. Louis',
  BIX: 'Biloxi',
  CIP: 'Chipley',
  CSV: 'Crestview',
  GUF: 'Gulfport',
  LEC: 'Lake City',
  MDO: 'Madison',
  MOE: 'Mobile',
  PAG: 'Pascagoula',
  PNS: 'Pensacola',
  TLH: 'Tallahassee',
  CBN: 'Canadian Border',
}

// Via Rail station code to IANA timezone database name map
// Source: https://www.viarail.ca/en/developer-resources → GTFS file → stops.txt
export const viaStationToTZDB: Record<string, string> = {
  BENN: 'America/Toronto',
  ALEX: 'America/Toronto',
  YONK: 'America/New_York',
  NIAG: 'America/New_York',
  OCHR: 'America/Winnipeg',
  WVHO: 'America/Winnipeg',
  SARN: 'America/Toronto',
  MJLI: 'America/Toronto',
  SLAM: 'America/Toronto',
  OROK: 'America/Winnipeg',
  MSNH: 'America/Vancouver',
  WNDG: 'America/Toronto',
  AGAS: 'America/Vancouver',
  THIB: 'America/Winnipeg',
  TELK: 'America/Vancouver',
  SMRB: 'America/Toronto',
  TIMB: 'America/Toronto',
  OBRI: 'America/Toronto',
  SIPI: 'America/Winnipeg',
  CEDA: 'America/Vancouver',
  HERC: 'America/Winnipeg',
  ROCH: 'America/New_York',
  BDNC: 'America/Toronto',
  BRMT: 'America/Toronto',
  LEVA: 'America/Toronto',
  USKX: 'America/Vancouver',
  BBAR: 'America/Vancouver',
  HOPE: 'America/Vancouver',
  OSKR: 'America/Toronto',
  CHIL: 'America/Vancouver',
  AMRY: 'America/Winnipeg',
  EDMO: 'America/Edmonton',
  GRNG: 'America/Toronto',
  HUTT: 'America/Vancouver',
  FITZ: 'America/Toronto',
  FING: 'America/Winnipeg',
  DYCE: 'America/Winnipeg',
  TOGO: 'America/Regina',
  JONQ: 'America/Toronto',
  SAVL: 'America/Winnipeg',
  ALWB: 'America/Winnipeg',
  AUDN: 'America/Toronto',
  FERL: 'America/Toronto',
  KAMS: 'America/Regina',
  MUDR: 'America/Toronto',
  ARMG: 'America/Toronto',
  FLTL: 'America/Winnipeg',
  GSTO: 'America/Winnipeg',
  COLL: 'America/Toronto',
  SANF: 'America/Toronto',
  STIT: 'America/Toronto',
  BIMA: 'America/Toronto',
  SSCC: 'America/Toronto',
  TRRC: 'America/Vancouver',
  PBDT: 'America/Toronto',
  VDRH: 'America/Vancouver',
  BRKV: 'America/Toronto',
  MALT: 'America/Toronto',
  DNST: 'America/Vancouver',
  CHBD: 'America/Toronto',
  OAKV: 'America/Toronto',
  HERV: 'America/Toronto',
  CHUR: 'America/Winnipeg',
  FFRA: 'America/Vancouver',
  LTUQ: 'America/Toronto',
  VDRY: 'America/Toronto',
  BRNL: 'America/Vancouver',
  WEIR: 'America/Winnipeg',
  PENN: 'America/Vancouver',
  DORV: 'America/Toronto',
  GEOR: 'America/Toronto',
  NAKI: 'America/Toronto',
  CARA: 'America/Toronto',
  HLSP: 'America/Toronto',
  BIRD: 'America/Winnipeg',
  LNDN: 'America/Toronto',
  OBAX: 'America/Toronto',
  LLAC: 'America/Toronto',
  SHPN: 'America/Toronto',
  HBAY: 'America/Regina',
  OTTM: 'America/Winnipeg',
  XYUL: 'America/Toronto',
  ATKL: 'America/Winnipeg',
  MUNK: 'America/Winnipeg',
  WAIN: 'America/Edmonton',
  NONS: 'America/Winnipeg',
  NEME: 'America/Toronto',
  UNIT: 'America/Regina',
  BUTT: 'America/Winnipeg',
  GRIM: 'America/Toronto',
  SYRA: 'America/New_York',
  TREM: 'America/Winnipeg',
  CRSM: 'America/Toronto',
  RDDT: 'America/Winnipeg',
  MNKI: 'America/Winnipeg',
  FARL: 'America/Winnipeg',
  GLNA: 'America/Winnipeg',
  RVRS: 'America/Winnipeg',
  OTTW: 'America/Toronto',
  HOUS: 'America/Vancouver',
  TPAS: 'America/Winnipeg',
  GMRE: 'America/Toronto',
  CNYK: 'America/Winnipeg',
  SPAU: 'America/Toronto',
  HRDL: 'America/Toronto',
  CHNY: 'America/Toronto',
  STGS: 'America/Regina',
  SCHE: 'America/New_York',
  MIQK: 'America/Toronto',
  FALR: 'America/Toronto',
  JASP: 'America/Edmonton',
  AMHS: 'America/Halifax',
  ROUS: 'America/Toronto',
  EARC: 'America/Winnipeg',
  DESS: 'America/Toronto',
  TURN: 'America/Winnipeg',
  DRLL: 'America/Toronto',
  LBOU: 'America/Toronto',
  NFNY: 'America/New_York',
  CORM: 'America/Winnipeg',
  SFOY: 'America/Toronto',
  DEVN: 'America/Toronto',
  LRIE: 'America/Winnipeg',
  QBEC: 'America/Toronto',
  MCGR: 'America/Vancouver',
  LWTH: 'America/Vancouver',
  LYDD: 'America/Winnipeg',
  MIKA: 'America/Regina',
  PIKW: 'America/Winnipeg',
  MCLI: 'America/Winnipeg',
  SMTF: 'America/Toronto',
  MSBI: 'America/Toronto',
  WDON: 'America/Toronto',
  CBAT: 'America/Toronto',
  ELSA: 'America/Toronto',
  CLOV: 'America/Toronto',
  BLGC: 'America/Toronto',
  MUSK: 'America/Toronto',
  LNGL: 'America/Toronto',
  CHRT: 'America/Toronto',
  CLWT: 'America/Vancouver',
  CAUS: 'America/Toronto',
  CHLO: 'America/Halifax',
  STRF: 'America/Toronto',
  TPIS: 'America/Toronto',
  BRQU: 'America/Toronto',
  ALZL: 'America/Vancouver',
  VBRU: 'America/Toronto',
  RAWE: 'America/Winnipeg',
  EVAN: 'America/Edmonton',
  POUG: 'America/New_York',
  BIGG: 'America/Regina',
  PITS: 'America/Winnipeg',
  POGA: 'America/Toronto',
  PRUP: 'America/Vancouver',
  SHWN: 'America/Toronto',
  SUDB: 'America/Toronto',
  HLFX: 'America/Halifax',
  GUIL: 'America/Toronto',
  HEBV: 'America/Toronto',
  PGEO: 'America/Vancouver',
  VKNG: 'America/Edmonton',
  OPHR: 'America/Winnipeg',
  JOLI: 'America/Toronto',
  LPRS: 'America/Winnipeg',
  CBRG: 'America/Toronto',
  KOND: 'America/Toronto',
  KWIN: 'America/Vancouver',
  AMST: 'America/New_York',
  DORR: 'America/Vancouver',
  MCTC: 'America/Toronto',
  RCLK: 'America/Winnipeg',
  LEDW: 'America/Toronto',
  MWWC: 'America/Toronto',
  COQU: 'America/Toronto',
  CHEL: 'America/Toronto',
  COPE: 'America/Winnipeg',
  LARC: 'America/Toronto',
  SCAT: 'America/Toronto',
  ALBY: 'America/New_York',
  SMYS: 'America/Toronto',
  TRUR: 'America/Halifax',
  MCTN: 'America/Halifax',
  BISC: 'America/Toronto',
  STRR: 'America/Toronto',
  RGRV: 'America/Halifax',
  JACR: 'America/Halifax',
  BRMP: 'America/Toronto',
  INGR: 'America/Toronto',
  RAPB: 'America/Toronto',
  CANN: 'America/Toronto',
  BUDD: 'America/Winnipeg',
  RDLX: 'America/Toronto',
  BOLK: 'America/Toronto',
  RMSK: 'America/Toronto',
  STRL: 'America/Toronto',
  BUFX: 'America/New_York',
  GANA: 'America/Toronto',
  LDAR: 'America/Toronto',
  SACK: 'America/Halifax',
  CHAP: 'America/Toronto',
  BRTL: 'America/Winnipeg',
  MCBR: 'America/Vancouver',
  ELMA: 'America/Winnipeg',
  JACC: 'America/Toronto',
  WEKU: 'America/Winnipeg',
  WSTR: 'America/Toronto',
  GOGA: 'America/Toronto',
  PROC: 'America/Halifax',
  FELX: 'America/Toronto',
  RUEL: 'America/Toronto',
  GUEL: 'America/Toronto',
  FOLE: 'America/Toronto',
  GLNC: 'America/Toronto',
  VCVR: 'America/Vancouver',
  NEWY: 'America/New_York',
  SMMC: 'America/Toronto',
  SIGN: 'America/Toronto',
  GARN: 'America/Toronto',
  FRNZ: 'America/Toronto',
  WOMR: 'America/Toronto',
  FORS: 'America/Toronto',
  DOMC: 'America/Vancouver',
  BLVL: 'America/Toronto',
  HIBB: 'America/Toronto',
  DALT: 'America/Toronto',
  VMLC: 'America/Toronto',
  DERI: 'America/Winnipeg',
  TRNJ: 'America/Toronto',
  DUNL: 'America/Winnipeg',
  CSLM: 'America/Toronto',
  GOAT: 'America/Vancouver',
  IRQC: 'America/Toronto',
  BOYD: 'America/Winnipeg',
  THKP: 'America/Winnipeg',
  CART: 'America/Toronto',
  BTRS: 'America/Halifax',
  PLUM: 'America/Winnipeg',
  RBRT: 'America/Toronto',
  PIPN: 'America/Winnipeg',
  GILL: 'America/Winnipeg',
  LPOC: 'America/Toronto',
  BGQU: 'America/Toronto',
  UTIC: 'America/New_York',
  OSHA: 'America/Toronto',
  NICH: 'America/Toronto',
  BEND: 'America/Vancouver',
  MCCR: 'America/Winnipeg',
  MEGI: 'America/Toronto',
  LUKE: 'America/Winnipeg',
  RTAC: 'America/Toronto',
  LOOS: 'America/Vancouver',
  WBDN: 'America/Winnipeg',
  WNPG: 'America/Winnipeg',
  FALL: 'America/Toronto',
  SPAR: 'America/Toronto',
  KITW: 'America/Vancouver',
  HNPN: 'America/Toronto',
  HRVY: 'America/Vancouver',
  LAFO: 'America/Toronto',
  ILFO: 'America/Winnipeg',
  PATE: 'America/Winnipeg',
  MNET: 'America/Toronto',
  CARI: 'America/Toronto',
  PACI: 'America/Vancouver',
  VLMT: 'America/Vancouver',
  EDSN: 'America/Edmonton',
  PRLL: 'America/Toronto',
  MELV: 'America/Regina',
  THOM: 'America/Winnipeg',
  DRMV: 'America/Toronto',
  SHYA: 'America/Toronto',
  CASS: 'America/Vancouver',
  ANJO: 'America/Toronto',
  AMYO: 'America/Toronto',
  SWAN: 'America/Toronto',
  WILD: 'America/Winnipeg',
  SENN: 'America/Toronto',
  WGWC: 'America/Toronto',
  GVIE: 'America/Winnipeg',
  KORM: 'America/Toronto',
  LEVN: 'America/Winnipeg',
  STAD: 'America/Toronto',
  MLCH: 'America/Winnipeg',
  KPTC: 'America/Toronto',
  KISK: 'America/Toronto',
  BRTF: 'America/Toronto',
  GAGN: 'America/Toronto',
  ALDR: 'America/Toronto',
  PHOP: 'America/Toronto',
  BUFF: 'America/New_York',
  ARNO: 'America/Winnipeg',
  CBTN: 'America/Halifax',
  ODHI: 'America/Winnipeg',
  ODAY: 'America/Winnipeg',
  COTO: 'America/Toronto',
  RAPX: 'America/Toronto',
  CASY: 'America/Toronto',
  TRTC: 'America/Toronto',
  GIRD: 'America/Toronto',
  MJBG: 'America/Toronto',
  MCCA: 'America/Toronto',
  CROT: 'America/New_York',
  MTGM: 'America/Toronto',
  DAUP: 'America/Winnipeg',
  NBND: 'America/Vancouver',
  SUDJ: 'America/Toronto',
  SINM: 'America/Vancouver',
  WYOM: 'America/Toronto',
  WDST: 'America/Toronto',
  KATZ: 'America/Vancouver',
  TIDL: 'America/Winnipeg',
  SHEA: 'America/Toronto',
  STRN: 'America/Toronto',
  HINT: 'America/Edmonton',
  PNTN: 'America/Winnipeg',
  RSRV: 'America/Regina',
  HUDS: 'America/New_York',
  MIRA: 'America/Halifax',
  SULT: 'America/Toronto',
  RAMS: 'America/Toronto',
  WNTB: 'America/Winnipeg',
  ASHN: 'America/Vancouver',
  BLUE: 'America/Vancouver',
  WSHG: 'America/Toronto',
  KGON: 'America/Toronto',
  PRSS: 'America/Toronto',
  MMGY: 'America/Toronto',
  LDES: 'America/Toronto',
  RBLN: 'America/Winnipeg',
  LIZO: 'America/Toronto',
  ROME: 'America/New_York',
  RCHN: 'America/Winnipeg',
  MCKC: 'America/Toronto',
  KAMN: 'America/Vancouver',
  WHTR: 'America/Toronto',
  RLRX: 'America/Winnipeg',
  MTPD: 'America/Toronto',
  CAPR: 'America/Toronto',
  PARS: 'America/Toronto',
  TRTO: 'America/Toronto',
  SASK: 'America/Regina',
  ESHR: 'America/Toronto',
  KINO: 'America/Toronto',
  DIXX: 'America/Toronto',
  DUPL: 'America/Toronto',
  ENDA: 'America/Vancouver',
  GLBP: 'America/Winnipeg',
  PARE: 'America/Toronto',
  WILR: 'America/Vancouver',
  NAPN: 'America/Toronto',
  VERE: 'America/Regina',
  OSKL: 'America/Toronto',
  UFRZ: 'America/Vancouver',
  SANM: 'America/Toronto',
  SMTR: 'America/Vancouver',
  ABBO: 'America/Vancouver',
  CHES: 'America/Winnipeg',
  WATR: 'America/Regina',
  NHAZ: 'America/Vancouver',
  MTRL: 'America/Toronto',
  PLPX: 'America/Winnipeg',
  RHIN: 'America/New_York',
  AMQU: 'America/Toronto',
  AZIL: 'America/Toronto',
  KITC: 'America/Toronto',
  LOCH: 'America/Toronto',
  CANO: 'America/Regina',
  HALC: 'America/Winnipeg',
  CHAT: 'America/Toronto',
  BRGR: 'America/Winnipeg',
  CWLL: 'America/Toronto',
  ENDV: 'America/Regina',
  HOCK: 'America/Winnipeg',
  FERG: 'America/Toronto',
  SAUV: 'America/Toronto',
  NCLC: 'America/Toronto',
  GRGC: 'America/Toronto',
  WYMT: 'America/Toronto',
  LMAL: 'America/Toronto',
  SMQU: 'America/Toronto',
  SLKT: 'America/Winnipeg',
  CHER: 'America/Toronto',
  SAYA: 'America/Toronto',
  SJUS: 'America/Toronto',
  SPRJ: 'America/Halifax',
  SNKR: 'America/Toronto',
  FRKS: 'America/Toronto',
}
