export const sourceId = {
  amtrakTrack: 'amtrak-track',
  amtrakStations: 'amtrak-stations',
  trains: 'trains',
}

// map from 2-letter code (arbitrarily chosen by me) to Amtraker API route name
export const codeToRouteMap: Record<string, string> = {
  AC: 'Acela',
  AD: 'Adirondack',
  CA: 'Amtrak Cascades',
  HL: 'Amtrak Hartford Line',
  AT: 'Auto Train',
  BF: 'Berkshire Flyer',
  BW: 'Blue Water',
  BR: 'Borealis',
  BL: 'Brightline',
  CZ: 'California Zephyr',
  CC: 'Capitol Corridor',
  CD: 'Cardinal',
  CL: 'Carolinian',
  NO: 'City of New Orleans',
  CS: 'Coast Starlight',
  CR: 'Crescent',
  DE: 'Downeaster',
  EB: 'Empire Builder',
  ES: 'Empire Service',
  EA: 'Ethan Allen Express',
  FL: 'Floridian',
  HF: 'Heartland Flyer',
  HW: 'Hiawatha',
  IL: 'Illini',
  IZ: 'Illinois Zephyr',
  KS: 'Keystone',
  LS: 'Lake Shore Limited',
  LN: 'Lincoln Service',
  LR: 'Lincoln River Runner',
  ML: 'Maple Leaf',
  MS: 'Michigan Services',
  MR: 'Missouri River Runner',
  NE: 'Northeast Regional',
  PM: 'Palmetto',
  PS: 'Pacific Surfliner',
  PA: 'Pennsylvanian',
  PD: 'Piedmont',
  SB: 'Carl Sandburg',
  SU: 'Saluki',
  SJ: 'San Joaquins',
  SM: 'Silver Meteor',
  SC: 'Southwest Chief',
  SL: 'Sunset Limited',
  TE: 'Texas Eagle',
  VF: 'Valley Flyer',
  VT: 'Vermonter',
  WP: 'Winter Park Express',
  WV: 'Wolverine',
}

export const routeToCodeMap = Object.fromEntries(
  Object.entries(codeToRouteMap).map(([code, route]) => [route, code]),
)
