export const sourceId = {
  amtrakTrack: 'amtrak-track',
  amtrakStations: 'amtrak-stations',
  trains: 'trains',
  trainGPS: 'train-gps',
}

// map from Amtrak API route name to 2-letter code (arbitrarily chosen by me)
export const routeToCodeMap: Record<string, string> = {
  Acela: 'AC',
  Adirondack: 'AD',
  'Amtrak Cascades': 'CA',
  'Amtrak Hartford Line': 'HL',
  'Auto Train': 'AT',
  'Berkshire Flyer': 'BF',
  'Blue Water': 'BW',
  'Blue Water/Michigan Service': 'BW',
  Borealis: 'BR',
  Brightline: 'BL',
  'California Zephyr': 'CZ',
  'Capitol Corridor': 'CC',
  Cardinal: 'CD',
  Carolinian: 'CL',
  'Carolinian / Piedmont': 'CL',
  'City of New Orleans': 'NO',
  'Coast Starlight': 'CS',
  Crescent: 'CR',
  Downeaster: 'DE',
  'Empire Builder': 'EB',
  'Empire Service': 'ES',
  'Ethan Allen Express': 'EA',
  Floridian: 'FL',
  'Gold Runner': 'GR',
  'Heartland Flyer': 'HF',
  Hiawatha: 'HW',
  Illini: 'IL',
  'Illinois Zephyr': 'IZ',
  Keystone: 'KS',
  'Lake Shore Limited': 'LS',
  'Lincoln Service': 'LN',
  'Lincoln Service Missouri River Runner': 'LN',
  'Lincoln River Runner': 'LR',
  'Maple Leaf': 'ML',
  'Mardi Gras Service': 'MG',
  'Michigan Services': 'MS',
  'Missouri River Runner': 'MR',
  'Northeast Regional': 'NE',
  Palmetto: 'PM',
  'Pacific Surfliner': 'PS',
  Pennsylvanian: 'PA',
  Piedmont: 'PD',
  'Carl Sandburg': 'SB',
  Saluki: 'SU',
  'Saluki/Illinois Service': 'SU',
  'San Joaquins': 'SJ',
  'Silver Meteor': 'SM',
  'Southwest Chief': 'SC',
  'Sunset Limited': 'SL',
  'Texas Eagle': 'TE',
  'Valley Flyer': 'VF',
  Vermonter: 'VT',
  'Winter Park Express': 'WP',
  Wolverine: 'WV',
  'Wolverine/Michigan Service': 'WV',
}

export const codeToRouteMap = Object.fromEntries(
  Object.entries(routeToCodeMap).map(([code, route]) => [route, code]),
)
